import type { Horse, CompetitionResult, Valuation } from '../types';
import { calculateValuation } from '../services/valuation';

const now = new Date().toISOString();

export const seedHorses: Horse[] = [
  {
    id: 'seed-01',
    feiId: '104QG57',
    name: 'Nonstop van de Lentamel',
    age: 10,
    breed: 'BWP',
    studbook: 'BWP',
    gender: 'stallion',
    color: 'Bay',
    country: 'BEL',
    sire: 'Chacco-Blue',
    dam: 'Wiolette van de Lentamel',
    damSire: 'Nabab de Rêve',
    rider: 'Gregory Wathelet',
    owner: 'Lentamel Stables',
    createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-02',
    feiId: '103WQ14',
    name: 'Luciana Z',
    age: 8,
    breed: 'Zangersheide',
    studbook: 'BWP',
    gender: 'mare',
    color: 'Grey',
    country: 'USA',
    sire: 'Lordanos',
    dam: 'Ucanna Z',
    damSire: 'Uriko',
    rider: 'Laura Kraut',
    owner: 'Hadley LLC',
    createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-03',
    feiId: '105BH22',
    name: 'Cornet du Lys',
    age: 12,
    breed: 'Selle Français',
    studbook: 'Selle Français',
    gender: 'stallion',
    color: 'Chestnut',
    country: 'FRA',
    sire: 'Cornet Obolensky',
    dam: 'Qualia du Lys',
    damSire: 'Voltaire',
    rider: 'Penelope Leprevost',
    owner: 'Haras du Lys',
    createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-04',
    feiId: '106TT99',
    name: 'Heartbeat K',
    age: 7,
    breed: 'KWPN',
    studbook: 'KWPN',
    gender: 'gelding',
    color: 'Dark Bay',
    country: 'NED',
    sire: 'Heartbreaker',
    dam: 'Ulastra K',
    damSire: 'Kannan',
    rider: 'Maikel van der Vleuten',
    owner: 'Koolstra Horses',
    createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-05',
    feiId: '107AX45',
    name: 'Zirocco Blue\'s Son',
    age: 9,
    breed: 'KWPN',
    studbook: 'KWPN',
    gender: 'stallion',
    color: 'Grey',
    country: 'NED',
    sire: 'Zirocco Blue VDL',
    dam: 'Anabelle VDL',
    damSire: 'Numero Uno',
    rider: 'Willem Greve',
    owner: 'VDL Stud',
    createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-06',
    feiId: '104MM87',
    name: 'Chica del Milagro',
    age: 6,
    breed: 'Oldenburg',
    studbook: 'Oldenburg',
    gender: 'mare',
    color: 'Bay',
    country: 'GER',
    sire: 'Comme il faut',
    dam: 'Dana del Milagro',
    damSire: 'Balou du Rouet',
    rider: 'Philipp Weishaupt',
    owner: 'Gestüt Milagro',
    createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-07',
    feiId: '105KR33',
    name: 'Kannan\'s Gold',
    age: 11,
    breed: 'Hanoverian',
    studbook: 'Hanoverian',
    gender: 'gelding',
    color: 'Bay',
    country: 'GER',
    sire: 'Kannan',
    dam: 'Golden Dream H',
    damSire: 'Contender',
    rider: 'Daniel Deusser',
    owner: 'Stephex Stables',
    createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-08',
    feiId: '106PP11',
    name: 'Verdi\'s Heir',
    age: 8,
    breed: 'Holsteiner',
    studbook: 'Holsteiner',
    gender: 'stallion',
    color: 'Chestnut',
    country: 'GER',
    sire: 'Verdi TN',
    dam: 'Quita la Silla',
    damSire: 'Cassini I',
    rider: 'Marcus Ehning',
    owner: 'Pfeffer GmbH',
    createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-09',
    feiId: '107BZ60',
    name: 'Conthargos Junior',
    age: 5,
    breed: 'Holsteiner',
    studbook: 'Holsteiner',
    gender: 'gelding',
    color: 'Grey',
    country: 'USA',
    sire: 'Conthargos',
    dam: 'Joline HH',
    damSire: 'Quidam de Revel',
    rider: 'McLain Ward',
    owner: 'Aber Family Farm',
    createdAt: now, updatedAt: now,
  },
  {
    id: 'seed-10',
    feiId: '105YL72',
    name: 'Messenger\'s Echo',
    age: 13,
    breed: 'KWPN',
    studbook: 'KWPN',
    gender: 'mare',
    color: 'Bay',
    country: 'BRA',
    sire: 'Messenger',
    dam: 'Elora VDL',
    damSire: 'Voltaire',
    rider: 'Carlos Eduardo Mota Lopes',
    owner: 'Haras Olímpico',
    createdAt: now, updatedAt: now,
  },
];

// Generate realistic competition results per horse
function makeResults(
  horseId: string,
  horseName: string,
  country: string,
  level: import('../types').JumpingLevel,
  count: number,
  clearRate: number
): CompetitionResult[] {
  const events = [
    'CSIO5* Aachen', 'CSI5* Geneva', 'CSI5* Wellington', 'CSI4* Madrid',
    'CSIO4* Rotterdam', 'CSI3* Barcelona', 'CSI4* Knokke', 'CSI5* Paris Longchamp',
    'CSI4* São Paulo', 'CSIO3* Buenos Aires', 'CSI5* New York', 'CSI4* Gothenburg',
    'CSIO5* La Baule', 'CSI4* Dublin', 'CSI3* Vilamoura',
  ];
  const results: CompetitionResult[] = [];
  for (let i = 0; i < count; i++) {
    const clear = Math.random() < clearRate;
    const date = new Date(Date.now() - Math.random() * 730 * 24 * 3600000);
    results.push({
      id: crypto.randomUUID(),
      horseId,
      horseName,
      eventName: events[Math.floor(Math.random() * events.length)],
      eventDate: date.toISOString().split('T')[0],
      level,
      placement: clear ? Math.floor(Math.random() * 8) + 1 : undefined,
      totalEntries: Math.floor(Math.random() * 30) + 15,
      faults: clear ? 0 : [4, 4, 8, 8, 4][Math.floor(Math.random() * 5)],
      time: 60 + Math.random() * 30,
      clear,
      country,
      source: 'MANUAL',
    });
  }
  return results;
}

export function buildSeedResults(): CompetitionResult[] {
  return [
    ...makeResults('seed-01', 'Nonstop van de Lentamel', 'BEL', 'GP*', 25, 0.68),
    ...makeResults('seed-02', 'Luciana Z', 'USA', '1.50m', 20, 0.72),
    ...makeResults('seed-03', 'Cornet du Lys', 'FRA', 'GP**', 30, 0.60),
    ...makeResults('seed-04', 'Heartbeat K', 'NED', '1.40m', 18, 0.78),
    ...makeResults('seed-05', 'Zirocco Blue\'s Son', 'NED', '1.50m', 22, 0.65),
    ...makeResults('seed-06', 'Chica del Milagro', 'GER', '1.30m', 14, 0.80),
    ...makeResults('seed-07', 'Kannan\'s Gold', 'GER', 'GP', 28, 0.62),
    ...makeResults('seed-08', 'Verdi\'s Heir', 'GER', '1.45m', 20, 0.70),
    ...makeResults('seed-09', 'Conthargos Junior', 'USA', '1.20m', 10, 0.85),
    ...makeResults('seed-10', 'Messenger\'s Echo', 'BRA', '1.50m', 24, 0.58),
  ];
}

export function buildSeedValuations(results: CompetitionResult[]): Valuation[] {
  return seedHorses.map((horse) => {
    const hr = results.filter((r) => r.horseId === horse.id);
    return calculateValuation(horse, hr);
  });
}
